language: python
os: linux
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
      before_install:
        - sudo apt-get update
        - sudo apt-get install libopenmpi-dev
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  # Install latest versions.
  - pip3 install coverage
  - pip3 install -e .
  - pip3 install glia_test_mods==0.0.3 --no-cache-dir
script:
  - coverage run -m unittest discover -v -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
