language: python
os: linux
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
      before_install:
        - sudo apt-get update
        - sudo apt-get install libopenmpi-dev
        - wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
        - sudo dpkg -i nrn-7.7.x86_64-linux.deb
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  # Install latest versions.
  - pip3 install coverage
  - pip3 install -e .
  - pip3 install glia_test_mods>=0.0.2
script:
  - coverage run -m unittest discover -v -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
