name: Build and test Glia

on: [push]

jobs:
  build:
    name: build py${{ matrix.py }}, NEURON ${{ matrix.nrn }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ["3.9", "3.10"]
        nrn: ["8.1.0", "8.2.3"]
        include:
          - py: "3.9"
            nrn: "8.0.2"
          - py: "3.11"
            nrn: "8.2.3"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install openmpi-bin libopenmpi-dev
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies & self
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --prefer-binary
        pip install NEURON==${{ matrix.nrn }}
        pip install -e .
    - name: Run package-free tests
      run: coverage run -p -m unittest -v
    - name: Install test package
      run: pip install ./tests/data/packages/glia_test_mods
    - name: Run serial tests
      run: coverage run -p -m unittest -v
    - name: Run parallel tests
      run: mpiexec -n 2 coverage run -p -m unittest -v
    - name: Upload coverage reports
      run: bash <(curl -s https://codecov.io/bash)
